#!/usr/bin/env python3
"""Executable guard for Jcode's Nix-only distribution contract."""

from __future__ import annotations

import json
import pathlib
import re
import tomllib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]

RETIRED_PATHS = (
    "ios",
    "docs/IOS_APP.md",
    ".github/workflows/ios.yml",
    ".github/workflows/ios-testflight.yml",
    "scripts/install.sh",
    "scripts/install.ps1",
    "scripts/uninstall.sh",
    "scripts/install_release.sh",
    "scripts/test_install_release.sh",
    "scripts/update_packages.sh",
    "scripts/quick-release.sh",
    "scripts/phone-server/testflight-setup.py",
    # F30-FIX-4: shared PATH helper for the retired curl|bash installer. Its
    # own header described keeping it in sync with install.sh, which no longer
    # exists; nothing sourced it.
    "scripts/lib/configure_path.sh",
)

ACTIVE_DISTRIBUTION_DOCS = (
    "README.md",
    "RELEASING.md",
    "docs/BRANCHING.md",
    "docs/NIX.md",
    "docs/WINDOWS.md",
    "docs/WRAPPERS.md",
    "docs/ONBOARDING_SANDBOX.md",
    "scripts/phone-server/README.md",
)

# F30-FIX-1: the scan is opt-out, not opt-in. An allowlist silently exempts
# every document nobody remembered to add, so the gate reported OK while never
# opening 31 of 39 active docs. These prefixes are historical records that
# describe retired channels on purpose; everything else tracked is scanned.
UNSCANNED_PREFIXES = (
    "docs/fork/",
    "docs/archive/",
    "changelog/",
    "CHANGELOG",
)

# Documents whose subject is the prohibition itself, so they must name the
# retired channels in order to forbid them. Keep this list tiny and explicit;
# each entry is a hole in the gate.
PROHIBITION_DOCS = (".apm/instructions/main.instructions.md",)

# Build outputs and vendored trees are not repository documentation. Skipping
# them by directory name keeps the walk equivalent to the tracked file set
# without needing git, which the hermetic Nix sandbox does not provide.
SKIPPED_DIRECTORIES = frozenset(
    {
        ".git",
        ".jj",
        "target",
        "node_modules",
        "result",
        ".direnv",
        "vendor",
    }
)

# The lowest number of documents a healthy scan reaches. This exists so that a
# future refactor which empties the corpus fails RED instead of reporting OK on
# zero files, which is the exact failure mode F30-FIX-1 was filed for.
MIN_SCANNED_ACTIVE_DOCS = 60

# F30-FIX-3: workflows inherited from upstream are kept byte-close to the fork
# point and are dispatch-only, so they are deliberately not linted. Every other
# workflow is fork-owned and must be. Listing the exemptions rather than the
# covered set means a newly added workflow is linted by default; the previous
# hardcoded lint list silently omitted governance-root.yml for three weeks.
UNLINTED_UPSTREAM_WORKFLOWS = frozenset({"ci.yml", "freebsd-smoke.yml"})

# F30-FIX-2: the substring list missed the AUR, curl-pipe, and PowerShell-pipe
# install idioms entirely. These are regexes rather than substrings because the
# plain-substring forms collide with ordinary prose and markdown tables ("| sh"
# matches a table cell; "jcode-bin" matches "<jcode-binary>").
FORBIDDEN_ACTIVE_DOC_PATTERNS = (
    ("AUR yay install", r"\byay\s+-S\b"),
    ("AUR paru install", r"\bparu\s+-S\b"),
    ("AUR -git package", r"\bjcode(?:-desktop)?-git\b"),
    # Boundary-anchored: the bare substring also matches "<jcode-binary>".
    ("AUR jcode-bin package", r"\bjcode-bin\b"),
    ("curl pipe to shell", r"\bcurl\b[^\n|]*\|\s*(?:sudo\s+)?(?:sh|bash|zsh)\b"),
    ("wget pipe to shell", r"\bwget\b[^\n|]*\|\s*(?:sudo\s+)?(?:sh|bash|zsh)\b"),
    (
        "PowerShell pipe to iex",
        r"\b(?:iwr|irm|Invoke-WebRequest|Invoke-RestMethod)\b[^\n|]*\|\s*"
        r"(?:iex|Invoke-Expression)\b",
    ),
)


# Generated agent-contract surfaces (AGENTS.md / CLAUDE.md) are compiled by the
# APM CLI from `.apm/instructions`, are gitignored, and exist only in checkouts
# where someone has run `apm compile`. They inherit the prohibition text
# verbatim from the primitive that PROHIBITION_DOCS already exempts, so scanning
# them re-flags the exact wording that forbids the retired channels. Detect them
# by their generator marker rather than by path: the set of generated files
# changes as instructions move, and a hardcoded list would be one more allowlist
# to forget to update.
#
# Bound on this exemption, verified by planting violations: a retired channel
# added to any non-exempt source primitive under `.apm/instructions` is still
# caught, so the only thing skipped is text typed directly into a generated
# file -- which is gitignored and overwritten by the next `apm compile`, and so
# cannot reach the repository.
GENERATED_CONTRACT_MARKER = "<!-- Generated by APM CLI"


def is_generated_contract(path: pathlib.Path) -> bool:
    """True for an APM-generated agent contract, which mirrors exempt text."""
    if path.name not in {"AGENTS.md", "CLAUDE.md"}:
        return False
    with path.open(encoding="utf-8", errors="ignore") as handle:
        head = handle.read(512)
    return GENERATED_CONTRACT_MARKER in head


def tracked_active_documents() -> list[str]:
    """Every active doc the distribution policy governs (opt-out).

    Walks the filesystem rather than shelling out to git: this suite also runs
    inside the hermetic `nix-distribution-policy` derivation, whose sandbox has
    neither a `.git` directory nor a `git` binary.
    """
    found: list[str] = []
    for path in ROOT.rglob("*.md"):
        relative = path.relative_to(ROOT).as_posix()
        if any(part in SKIPPED_DIRECTORIES for part in path.relative_to(ROOT).parts[:-1]):
            continue
        if relative.startswith(UNSCANNED_PREFIXES) or relative in PROHIBITION_DOCS:
            continue
        if is_generated_contract(path):
            continue
        found.append(relative)
    instructions = ROOT / ".apm/instructions"
    if instructions.is_dir():
        for path in sorted(instructions.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(ROOT).as_posix()
            if relative not in PROHIBITION_DOCS:
                found.append(relative)
    return sorted(found)

FORBIDDEN_ACTIVE_DOC_TEXT = (
    "scripts/install.sh",
    "scripts/install.ps1",
    "scripts/uninstall.sh",
    "scripts/update_packages.sh",
    "scripts/quick-release.sh",
    "brew install jcode",
    "brew tap 1jehuang/jcode",
    "jcode update installs",
    "docs/IOS_APP.md",
    ".github/workflows/ios.yml",
    "native iOS application version",
    "jcode iOS app",
    "jcode://pair",
    "--option eval-cores",
)


class NixOnlyDistributionPolicy(unittest.TestCase):
    def test_retired_paths_are_absent(self) -> None:
        for relative in RETIRED_PATHS:
            with self.subTest(path=relative):
                self.assertFalse((ROOT / relative).exists(), f"retired path returned: {relative}")

    def test_native_ios_product_is_retired(self) -> None:
        self.assertTrue((ROOT / "web/jcode-mobile/index.html").is_file())
        package = (ROOT / "nix/package.nix").read_text()
        self.assertIn("web/jcode-mobile", package)

        banned_tokens = ("jcode://pair", "apns_token", "JCodeMobile", "APPSTORE_API_KEY")
        active_roots = (ROOT / "src", ROOT / "crates", ROOT / "scripts", ROOT / ".github/workflows")
        for root in active_roots:
            for path in root.rglob("*"):
                if not path.is_file():
                    continue
                text = path.read_text(errors="ignore")
                for token in banned_tokens:
                    with self.subTest(path=path.relative_to(ROOT), token=token):
                        self.assertNotIn(token, text)

    def test_release_workflow_is_metadata_only(self) -> None:
        workflow = (ROOT / ".github/workflows/release.yml").read_text()
        self.assertIn("metadata-only GitHub release", workflow)
        self.assertIn("must not contain binary assets", workflow)
        # release.yml owns its own v* tag trigger. Chaining it from nix.yml
        # via workflow_call forced a contents:write grant into the PR Gate call
        # tree, which GitHub rejects at workflow load (startup_failure on every
        # pull request). The two tag-triggered workflows run independently.
        self.assertIn("tags:", workflow)
        for banned in (
            "actions/upload-artifact",
            "actions/download-artifact",
            "gh release upload",
            "SHA256SUMS",
            "Homebrew",
            "AUR",
            "cargo build",
            ".tar.gz",
            "TestFlight",
        ):
            with self.subTest(token=banned):
                self.assertNotIn(banned, workflow)

    def test_no_workflow_publishes_non_nix_binaries(self) -> None:
        banned_tokens = (
            "gh release upload",
            "xcodebuild archive",
            "-exportArchive",
            "APPSTORE_API_KEY",
            "JCodeMobile",
            "xcodebuild",
            "notarytool submit",
            "cargo publish",
            "DeterminateSystems/nix-installer-action",
            "flakehub",
            "eval-cores",
        )
        workflow_dir = ROOT / ".github/workflows"
        workflows = list(workflow_dir.glob("*.yml")) + list(workflow_dir.glob("*.yaml"))
        for workflow in workflows:
            text = workflow.read_text()
            for banned in banned_tokens:
                with self.subTest(workflow=workflow.name, token=banned):
                    self.assertNotIn(banned, text)

    def test_nix_and_cachix_are_the_binary_authority(self) -> None:
        flake = (ROOT / "flake.nix").read_text()
        nix_workflow = (ROOT / ".github/workflows/nix.yml").read_text()
        self.assertIn("jerudnik-jcode.cachix.org", flake)
        self.assertIn("packages", flake)
        self.assertIn('tags: ["v*"]', nix_workflow)
        self.assertIn("cachix/cachix-action", nix_workflow)
        self.assertIn("cachix/install-nix-action@v31", nix_workflow)
        self.assertIn("Require Cachix publication for release tags", nix_workflow)
        self.assertIn("nix build .#packages.${{ matrix.system }}.jcode", nix_workflow)
        self.assertIn("needs: [validate, build]", nix_workflow)
        # nix.yml must not call release.yml: that chain is what injected a
        # contents:write requirement into the PR Gate call tree.
        self.assertNotIn("uses: ./.github/workflows/release.yml", nix_workflow)
        self.assertNotIn("ios.yml", nix_workflow)
        self.assertIn("retiredPathViolations", flake)
        self.assertIn("builtins.pathExists ./ios", flake)
        self.assertIn("builtins.pathExists ./docs/IOS_APP.md", flake)
        self.assertIn('if [ -n "$retiredPathViolations" ]', flake)

    def test_package_identity_stays_separate_from_exact_provenance(self) -> None:
        flake = (ROOT / "flake.nix").read_text()
        package = (ROOT / "nix/package.nix").read_text()

        self.assertIn("inherit craneLib version;", flake)
        self.assertNotIn("gitHash = inputs.self.shortRev or inputs.self.dirtyShortRev or \"nix\";", flake)
        self.assertNotIn("gitHash ?", package)
        self.assertNotIn("gitDate ?", package)
        self.assertNotIn("JCODE_BUILD_GIT_HASH", package)
        self.assertNotIn("JCODE_BUILD_GIT_DATE", package)
        self.assertIn("JCODE_BUILD_GIT_DIRTY", package)
        self.assertIn('sourceFullRevision = inputs.self.rev or inputs.self.dirtyRev or "unknown";', flake)
        self.assertIn("sourceDisplayRevision =", flake)
        self.assertIn("jcode-provenance = pkgs.callPackage ./nix/provenance.nix", flake)
        self.assertIn("packages.<system>.jcode", (ROOT / "docs/NIX.md").read_text())

    def test_runtime_update_commands_cannot_acquire_or_replace_jcode(self) -> None:
        update = (ROOT / "crates/jcode-app-core/src/update.rs").read_text()
        hot_exec = (ROOT / "src/cli/hot_exec.rs").read_text()
        tui_maintenance = (ROOT / "crates/jcode-tui/src/tui/app/state_ui_maintenance.rs").read_text()

        self.assertIn("NIX_UPDATE_GUIDANCE", update)
        self.assertIn("NIX_UPDATE_GUIDANCE", hot_exec)
        self.assertIn("NIX_UPDATE_GUIDANCE", tui_maintenance)
        for banned in (
            "download_and_install",
            "verify_asset_checksum",
            "SHA256SUMS",
            "releases/download",
            "api.github.com",
            "reqwest",
        ):
            with self.subTest(token=banned):
                self.assertNotIn(banned, update)

        runtime_sources = list((ROOT / "src").rglob("*.rs")) + list(
            (ROOT / "crates").rglob("*.rs")
        )
        for source in runtime_sources:
            text = source.read_text()
            for banned in (
                "api.github.com/repos/1jehuang/jcode/releases",
                "github.com/1jehuang/jcode/releases/download",
                "github.com/jerudnik/jcode/releases/download",
            ):
                with self.subTest(source=source.relative_to(ROOT), token=banned):
                    self.assertNotIn(banned, text)

    def test_retired_update_flags_have_no_active_callers(self) -> None:
        retired_flags = ("--no" + "-update", "--auto" + "-update")
        roots = ("scripts", "tests", "src", "crates", ".github/workflows")
        suffixes = {".py", ".sh", ".rs", ".yml", ".yaml"}
        for root in roots:
            for path in (ROOT / root).rglob("*"):
                if not path.is_file() or path.suffix not in suffixes:
                    continue
                text = path.read_text(errors="ignore")
                for flag in retired_flags:
                    with self.subTest(path=path.relative_to(ROOT), flag=flag):
                        self.assertNotIn(flag, text)

    def test_workspace_crates_cannot_publish_to_a_registry(self) -> None:
        root_manifest = tomllib.loads((ROOT / "Cargo.toml").read_text())
        members = root_manifest["workspace"]["members"]
        missing: list[str] = []
        for member in members:
            manifest = ROOT / member / "Cargo.toml" if member != "." else ROOT / "Cargo.toml"
            package = tomllib.loads(manifest.read_text()).get("package", {})
            if package.get("publish") is not False:
                missing.append(str(manifest.relative_to(ROOT)))
        self.assertEqual([], missing, f"workspace crates missing `publish = false`: {missing}")

    def test_active_distribution_docs_do_not_advertise_retired_channels(self) -> None:
        for relative in ACTIVE_DISTRIBUTION_DOCS:
            path = ROOT / relative
            self.assertTrue(path.exists(), f"active distribution document missing: {relative}")

        for relative in tracked_active_documents():
            text = (ROOT / relative).read_text(errors="ignore")
            for banned in FORBIDDEN_ACTIVE_DOC_TEXT:
                with self.subTest(path=relative, token=banned):
                    self.assertNotIn(banned, text, f"{relative} advertises retired channel {banned!r}")

    def test_retired_install_idioms_are_absent_from_active_docs(self) -> None:
        """F30-FIX-2: AUR, curl-pipe, and PowerShell-pipe install instructions."""
        for relative in tracked_active_documents():
            text = (ROOT / relative).read_text(errors="ignore")
            for label, pattern in FORBIDDEN_ACTIVE_DOC_PATTERNS:
                with self.subTest(path=relative, token=label):
                    match = re.search(pattern, text)
                    self.assertIsNone(
                        match,
                        f"{relative} advertises a retired install channel "
                        f"({label}): {match.group(0) if match else ''!r}",
                    )

    def test_every_fork_owned_workflow_is_lint_covered(self) -> None:
        """F30-FIX-3: lint coverage is a rule, not a hand-maintained list."""
        workflow_dir = ROOT / ".github/workflows"
        present = {path.name for path in workflow_dir.glob("*.yml")}
        present |= {path.name for path in workflow_dir.glob("*.yaml")}
        expected = present - UNLINTED_UPSTREAM_WORKFLOWS

        nix_workflow = (ROOT / ".github/workflows/nix.yml").read_text()
        flake = (ROOT / "flake.nix").read_text()
        for name in sorted(expected):
            reference = f".github/workflows/{name}"
            with self.subTest(workflow=name, list="nix.yml actionlint"):
                self.assertIn(
                    reference,
                    nix_workflow,
                    f"fork-owned workflow {name} is not linted by nix.yml",
                )
            with self.subTest(workflow=name, list="flake workflow-syntax check"):
                self.assertIn(
                    reference,
                    flake,
                    f"fork-owned workflow {name} is not linted by the flake check",
                )

        for name in sorted(UNLINTED_UPSTREAM_WORKFLOWS):
            with self.subTest(workflow=name, exemption="still present"):
                self.assertIn(
                    name,
                    present,
                    f"exempt workflow {name} no longer exists; drop it from "
                    "UNLINTED_UPSTREAM_WORKFLOWS instead of leaving a dead exemption",
                )

    def test_distribution_doc_scan_is_not_vacuous(self) -> None:
        """A gate that scans nothing reports OK. Make that state fail RED."""
        scanned = tracked_active_documents()
        self.assertGreaterEqual(
            len(scanned),
            MIN_SCANNED_ACTIVE_DOCS,
            f"distribution doc scan collapsed to {len(scanned)} files; "
            "the gate is near-vacuous and would pass without checking anything",
        )
        for relative in ACTIVE_DISTRIBUTION_DOCS:
            self.assertIn(relative, scanned, f"historically guarded doc dropped out: {relative}")

    def test_advertised_platform_support_matches_what_ci_builds(self) -> None:
        """G01: a flake system CI never builds must be documented best-effort.

        `flake.nix` `systems` is not only advertising -- it is what makes
        `packages.<system>.*` and `checks.<system>.*` exist, so a consumer can
        pin an output for a system no CI job has ever built. That is legitimate,
        but it must not read as the same level of support as a system that is
        built, smoke-launched, and pushed to Cachix on every change. Before this
        guard, docs/NIX.md listed all three flake systems in one flat sentence
        while `aarch64-linux` had never been built by any workflow.
        """
        matrix = json.loads((ROOT / ".github/workflows/build-matrix.json").read_text())
        built = {
            entry["system"]
            for key, entries in matrix.items()
            if not key.startswith("_")
            for entry in entries
        }
        flake = (ROOT / "flake.nix").read_text()
        systems_block = re.search(r"systems\s*=\s*\[(.*?)\]", flake, re.DOTALL)
        self.assertIsNotNone(systems_block, "could not locate `systems` in flake.nix")
        exposed = set(re.findall(r'"([^"]+)"', systems_block.group(1)))

        # Vacuity guards: both sides are parsed out of files that can be
        # reworded. An empty set on either side would make every assertion
        # below pass while checking nothing, which is the defect this whole
        # suite exists to prevent.
        self.assertGreaterEqual(len(built), 2, f"CI build matrix parsed to {built!r}")
        self.assertGreaterEqual(len(exposed), 2, f"flake systems parsed to {exposed!r}")
        self.assertTrue(
            built <= exposed,
            f"CI builds systems the flake does not expose: {sorted(built - exposed)}",
        )

        nix_doc = (ROOT / "docs/NIX.md").read_text()
        support_section = re.search(
            r"^## Supported platforms$(.*?)^## ", nix_doc, re.DOTALL | re.MULTILINE
        )
        self.assertIsNotNone(support_section, "docs/NIX.md lost its Supported platforms section")
        support_text = support_section.group(1)

        for system in sorted(exposed):
            with self.subTest(system=system):
                self.assertIn(
                    system,
                    support_text,
                    f"flake exposes {system} but docs/NIX.md does not state its support status",
                )

        # The actual rule: unbuilt systems must be marked, built ones must not.
        # Match any line naming the system, not a table row: the contract is
        # honest labeling, not a particular markdown shape. A flat sentence
        # listing several systems together still fails, and should -- one line
        # cannot state two different support levels.
        def status_line(system: str) -> str | None:
            return next(
                (line for line in support_text.splitlines() if system in line),
                None,
            )

        for system in sorted(exposed - built):
            row = status_line(system)
            with self.subTest(system=system, status="unbuilt"):
                self.assertIsNotNone(row, f"{system} needs a status line in docs/NIX.md")
                self.assertIn(
                    "Best-effort",
                    row,
                    f"{system} is exposed by the flake but no CI job builds it; "
                    "docs/NIX.md must mark it Best-effort rather than implying "
                    "it is verified like the systems CI actually builds",
                )
        for system in sorted(built):
            row = status_line(system)
            with self.subTest(system=system, status="built"):
                self.assertIsNotNone(row, f"{system} needs a status line in docs/NIX.md")
                self.assertNotIn(
                    "Best-effort",
                    row,
                    f"{system} is built by CI but documented Best-effort; "
                    "promote the row now that evidence exists",
                )


if __name__ == "__main__":
    unittest.main(verbosity=2)
