"""Regression tests for stale generated agent files."""

import importlib.util
import subprocess
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CHECKER_PATH = REPO_ROOT / "scripts" / "check_agent_instructions.py"


def load_checker():
    spec = importlib.util.spec_from_file_location("check_agent_instructions", CHECKER_PATH)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


class CheckAgentInstructionsTest(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="check-agent-instructions-")
        self.root = Path(self.temp.name)
        self.primitive = self.root / "primitive.instructions.md"
        self.primitive.write_text(
            '---\napplyTo: "**"\n---\n\nnew generated body\n',
            encoding="utf-8",
        )
        (self.root / ".gitignore").write_text("CLAUDE.md\n", encoding="utf-8")
        subprocess.run(["git", "init", "-q"], cwd=self.root, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.invalid"], cwd=self.root, check=True)
        subprocess.run(["git", "config", "user.name", "Test"], cwd=self.root, check=True)
        subprocess.run(["git", "add", ".gitignore", self.primitive.name], cwd=self.root, check=True)
        subprocess.run(["git", "commit", "-qm", "fixture"], cwd=self.root, check=True)
        self.checker = load_checker()
        self.checker.ROOT = self.root
        original_read = self.checker.read
        self.checker.read = lambda relative, root=None: original_read(relative, self.root)
        self.checker.ROOT_PRIMITIVES = (self.primitive.relative_to(self.root),)
        self.checker.CHILD_GENERATED = {}
        self.checker.JCODE_PROMPTS = ()
        self.checker.REQUIRED_PATHS = ()

    def tearDown(self):
        self.temp.cleanup()

    def write_stale_claude(self):
        (self.root / "CLAUDE.md").write_text(
            "# CLAUDE.md\n"
            "<!-- Generated by APM CLI -->\n"
            "\n"
            "# Project Standards\n\n"
            "## Files matching `**`\n\n"
            "stale generated body\n",
            encoding="utf-8",
        )

    def test_stale_untracked_claude_is_regenerated_and_passes(self):
        self.write_stale_claude()

        result = self.checker.main()

        self.assertEqual(result, 0)
        self.assertIn("new generated body", (self.root / "CLAUDE.md").read_text(encoding="utf-8"))
        self.assertNotIn("stale generated body", (self.root / "CLAUDE.md").read_text(encoding="utf-8"))

    def test_stale_tracked_claude_fails_and_is_unchanged(self):
        self.write_stale_claude()
        subprocess.run(["git", "add", "-f", "CLAUDE.md"], cwd=self.root, check=True)
        subprocess.run(["git", "commit", "-qm", "tracked claude"], cwd=self.root, check=True)
        before = (self.root / "CLAUDE.md").read_text(encoding="utf-8")

        result = self.checker.main()

        self.assertNotEqual(result, 0)
        self.assertEqual(before, (self.root / "CLAUDE.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
