[package]
name = "jcode-provider-anthropic"
version = "0.1.0"
publish = false
edition = "2024"

[dependencies]
jcode-logging = { path = "../jcode-logging" }
jcode-message-types = { path = "../jcode-message-types" }
jcode-provider-core = { path = "../jcode-provider-core" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
anyhow = "1"
async-trait = "0.1"
jcode-app-core = { path = "../jcode-app-core", default-features = false }
jcode-tool-types = { path = "../jcode-tool-types" }
serde_ignored = "0.1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
