#!/usr/bin/env python3
"""Validate the repository's agent-instruction contract without external tools."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Keep project-loaded policy compact enough to leave room for system and task
# context. Warn before the hard 8 KiB ceiling so normal edits do not hit it
# without notice.
PROMPT_BUDGET_BYTES = 8 * 1024
PROMPT_WARNING_BYTES = PROMPT_BUDGET_BYTES - 256
GENERATED_AGENTS_OVERHEAD_BYTES = 512

ROOT_PRIMITIVES = (
    Path(".apm/instructions/dox.instructions.md"),
    Path(".apm/instructions/fork-branch-rails.instructions.md"),
    Path(".apm/instructions/main.instructions.md"),
)
CHILD_GENERATED = {
    Path(".apm/AGENTS.md"): Path(".apm/instructions/dox-apm.instructions.md"),
    Path("docs/AGENTS.md"): Path(".apm/instructions/dox-docs.instructions.md"),
    Path("crates/jcode-desktop/AGENTS.md"): Path(
        ".apm/instructions/dox-desktop.instructions.md"
    ),
}
JCODE_PROMPTS = (
    Path(".jcode/preferred-tools.md"),
    Path(".jcode/prompt-overlay.md"),
    Path(".jcode/swarm-prompt.md"),
)
REQUIRED_PATHS = ROOT_PRIMITIVES + tuple(CHILD_GENERATED.values()) + JCODE_PROMPTS + (
    Path("docs/agent-workflows.md"),
    Path("docs/BRANCHING.md"),
    Path("docs/NIX.md"),
    Path("docs/SWARM_ARCHITECTURE.md"),
    Path("docs/SWARM_TASK_GRAPH.md"),
    Path("CONTRIBUTING.md"),
    Path("RELEASING.md"),
    Path("scripts/dev_cargo.sh"),
    Path("scripts/docs_impact_advisory.py"),
    Path("scripts/test_fast.sh"),
    Path("scripts/test_docs_impact_advisory.py"),
    Path("scripts/preflight.sh"),
    Path("scripts/remote_build.sh"),
    Path("scripts/clean_target.sh"),
    Path("scripts/prune_incremental.sh"),
    Path("scripts/test_incremental_policy.sh"),
    Path(".github/workflows/docs-impact.yml"),
    Path(".github/workflows/fork-ci.yml"),
    Path(".github/workflows/nix.yml"),
    Path(".github/workflows/security.yml"),
    Path(".github/workflows/release.yml"),
)


def read(relative: Path, root: Path = ROOT) -> str:
    return (root / relative).read_text(encoding="utf-8")


def primitive(relative: Path, root: Path = ROOT) -> tuple[str, str]:
    text = read(relative, root)
    parts = text.split("---", 2)
    if len(parts) != 3 or parts[0].strip():
        raise ValueError(f"{relative}: missing YAML frontmatter")
    match = re.search(r'^applyTo:\s*["\']?([^"\'\n]+)["\']?\s*$', parts[1], re.MULTILINE)
    if match is None:
        raise ValueError(f"{relative}: missing applyTo frontmatter")
    return match.group(1).strip(), parts[2].lstrip("\n")


def local_markdown_links(relative: Path) -> list[Path]:
    text = read(relative)
    links: list[Path] = []
    for target in re.findall(r"(?<!!)\[[^]]*]\(([^)]+)\)", text):
        target = target.split(maxsplit=1)[0].strip("<>")
        if not target or target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        path_text = target.split("#", 1)[0]
        links.append((ROOT / relative).parent.joinpath(path_text).resolve())
    return links


def compiled_body(text: str, apply_to: str) -> str:
    start_marker = f"## Files matching `{apply_to}`\n\n"
    end_marker = "\n\n---\n*This file was generated by APM CLI."
    if start_marker not in text or end_marker not in text:
        raise ValueError("AGENTS.md: unrecognized APM-generated format; regenerate with apm compile")
    return text.split(start_marker, 1)[1].split(end_marker, 1)[0].strip()


def main() -> int:
    errors: list[str] = []

    for relative in REQUIRED_PATHS:
        if not (ROOT / relative).exists():
            errors.append(f"missing required path: {relative}")

    bodies: list[str] = []
    for relative in ROOT_PRIMITIVES:
        try:
            apply_to, body = primitive(relative)
            if apply_to != "**":
                raise ValueError(f"{relative}: root primitive must use applyTo: \"**\"")
            bodies.append(body)
        except (OSError, ValueError) as error:
            errors.append(str(error))

    prompt_sources = list(ROOT_PRIMITIVES) + list(CHILD_GENERATED.values()) + list(JCODE_PROMPTS)
    for relative in prompt_sources:
        if (ROOT / relative).exists() and "```" in read(relative):
            errors.append(
                f"{relative}: prompt-loaded policy must not contain fenced command blocks; "
                "put operational commands in docs/agent-workflows.md"
            )

    agents_path = ROOT / "AGENTS.md"
    jcode_bytes = sum(len(read(path).encode("utf-8")) for path in JCODE_PROMPTS if (ROOT / path).exists())
    projected_agents_bytes = (
        sum(len(body.encode("utf-8")) for body in bodies) + GENERATED_AGENTS_OVERHEAD_BYTES
    )
    compiled_prompt_bytes: int | None = None
    if agents_path.exists():
        agents_text = agents_path.read_text(encoding="utf-8")
        compiled_prompt_bytes = agents_path.stat().st_size + jcode_bytes
        try:
            observed_body = compiled_body(agents_text, "**")
            expected_body = "\n\n".join(body.strip() for body in bodies)
            if observed_body != expected_body:
                errors.append("AGENTS.md is stale; run apm compile")
        except ValueError as error:
            errors.append(str(error))

    for generated, source in CHILD_GENERATED.items():
        generated_path = ROOT / generated
        if not generated_path.exists() or not (ROOT / source).exists():
            continue
        try:
            apply_to, expected_body = primitive(source)
            observed_body = compiled_body(
                generated_path.read_text(encoding="utf-8"), apply_to
            )
            if observed_body != expected_body.strip():
                errors.append(f"{generated} is stale; run apm compile")
        except (OSError, ValueError) as error:
            errors.append(str(error))
    prompt_bytes = projected_agents_bytes + jcode_bytes
    if prompt_bytes > PROMPT_BUDGET_BYTES:
        errors.append(
            f"projected prompt budget exceeded: {prompt_bytes} > {PROMPT_BUDGET_BYTES} bytes"
        )
    if compiled_prompt_bytes is not None and compiled_prompt_bytes > PROMPT_BUDGET_BYTES:
        errors.append(
            "compiled prompt budget exceeded: "
            f"{compiled_prompt_bytes} > {PROMPT_BUDGET_BYTES} bytes"
        )
    observed_prompt_bytes = max(prompt_bytes, compiled_prompt_bytes or 0)
    if observed_prompt_bytes > PROMPT_WARNING_BYTES:
        print(
            "agent-instructions: warning: prompt budget has less than 256 bytes free: "
            f"{observed_prompt_bytes}/{PROMPT_BUDGET_BYTES} bytes",
            file=sys.stderr,
        )

    workflows = Path("docs/agent-workflows.md")
    if (ROOT / workflows).exists():
        for target in local_markdown_links(workflows):
            if not target.exists():
                errors.append(f"{workflows}: broken local link to {target.relative_to(ROOT)}")

    required_text = {
        Path(".apm/instructions/main.instructions.md"): (
            "docs/agent-workflows.md",
            ".jcode/preferred-tools.md",
            "swarm list_models",
        ),
        Path(".jcode/prompt-overlay.md"): ("docs/agent-workflows.md",),
        Path(".jcode/swarm-prompt.md"): ("swarm list_models",),
    }
    for relative, needles in required_text.items():
        if not (ROOT / relative).exists():
            continue
        text = read(relative)
        for needle in needles:
            if needle not in text:
                errors.append(f"{relative}: missing required reference {needle!r}")

    if errors:
        for error in errors:
            print(f"agent-instructions: {error}", file=sys.stderr)
        return 1

    detail = f"projected={prompt_bytes}/{PROMPT_BUDGET_BYTES}"
    if compiled_prompt_bytes is not None:
        detail += f", compiled={compiled_prompt_bytes}/{PROMPT_BUDGET_BYTES}"
    print(f"agent-instructions: ok ({detail})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
